language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t snjanbu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true snjanbu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react
  env: Dockerreact-env
  bucket_name: "elasticbeanstalk-us-west-2-185619739661"
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: "$SECRET_ACCESS_KEY"